### ISSUE TITLE
/camera/color/image_raw/compressed no image showed

### ISSUE THREAD

**Issue by beyondli** [KavenYau/ros2_astra_camera#6]
Hi 
I found topic /camera/color/image_raw/compressed no image showed in rviz2, only /camera/color/image_raw worked, how to modify ocde that compressed can be worked?
thanks

**Comment by KavenYau** [comment]
https://github.com/KavenYau/ros2_astra_camera/blob/f230765cd1efbc0d4408b4978483cd1c76892ff3/ros2_astra_camera/src/camera_driver.cpp#L31-L32

I only create a CameraPublisher of topic `camera/color/image_raw` and publish uncompressed images. I have not try to dig out  how to get compressed images. Do you know something about this?

**Comment by KavenYau** [comment]
@beyondli Hi, I found something you might be interested. I am trying to use this package in WSL2(Ubuntu 22.04) + ROS2 Humble + usbipd environment. With applying this patch(https://github.com/KavenYau/ros2_astra_camera/commit/39433ab9bc35ecfdc200e9d4504ba7ac55471aab), I can get images from topic `camera/color/image_raw/compressed`. But I not sure whether it works in pure Ubuntu.

![image](https://user-images.githubusercontent.com/24326888/208289747-ce33d5e6-cae7-4be0-b444-34d6fa8d35e0.png)

The `astra_pro.yaml` I used is:
```yaml
astra_camera_node:
  ros__parameters:
    auto_exposure: true
    auto_white_balance: true
    color_depth_synchronization: false
    ir_frame_id: camera_ir_optical_frame
    rgb_frame_id: camera_rgb_optical_frame
    color_time_offset: -0.033
    data_skip: 0
    depth_camera_info_url: ''
    depth_frame_id: camera_depth_optical_frame
    depth_ir_offset_x: 5.0
    depth_ir_offset_y: 4.0
    depth_mode: 7
    depth_registration: true
    depth_time_offset: 0.0
    device_id: '#1'
    ir_mode: 7
    ir_time_offset: -0.033
    rgb_camera_info_url: ''
    rgb_preferred: true
    use_color: false
    use_depth: true
    use_device_time: false
    use_ir: true
    use_sim_time: false
    z_offset_mm: 0.0
    z_scaling: 1.0

uvc_camera_node:
  ros__parameters:
    vendor: "0x2bc5"
    product: "0x0502"
    serial: ""
    index: 0
    width: 640
    height: 480
    # video_mode: mjpeg
    video_mode: compressed # uncompressed
    frame_rate: 30.0
    timestamp_method: start
    frame_id: camera
    camera_info_url: ""
    scanning_mode: 0
    auto_exposure: 3
```
